spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  jackson:
    serialization:
      INDENT_OUTPUT: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  reactor:
    debug-agent:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  docker:
    compose:
      enabled: false

server:
  tomcat:
    accesslog:
      enabled: true
    basedir: logs/

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
